version: "3"

services:
  nodejs-devenv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-devenv
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_VERSION=15.3.2 # 環境変数としてもバージョンを設定
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-devenv
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: nodejs-postgres-data
