version: '3'

services:
  nextjs-15-3-2:  # サービス名にバージョンを含める
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-15-3-2-dev  # コンテナ名にバージョンを含める
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_VERSION=15.3.2  # 環境変数としてもバージョンを設定
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-15-nextjs  # PostgreSQLのバージョンも含める
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: nextjs-15-3-2-postgres-data  # ボリューム名にもバージョンを含める
