services:
  nodejs-devenv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-devenv
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_VERSION=15.3.2
    command: sh -c "npm run dev -- --hostname 0.0.0.0"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-devenv
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: nodejs-postgres-data

networks:
  default:
    driver: bridge # ← enable_ipv6 が不要ならこの 2 行だけでもよい
    enable_ipv6: false
