services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-devenv
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_VERSION=15.3.2
    - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres_db
    command: sh -c "npm run dev -- --hostname 0.0.0.0"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-devenv
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: nodejs-postgres-data
  node_modules:

networks:
  default:
    driver: bridge # ← enable_ipv6 が不要ならこの 2行だけでもよい
    enable_ipv6: false
